config/routes.rb
App::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }, 
    :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}
	
	devise_scope :user do
		post 'token_sessions' => 'token_sessions#create', :as => 'login'
		delete 'token_sessions' => 'token_sessions#destroy', :as => 'logout'
	end

	resources :accounts
	
	post 'upload_locations' => 'locations_upload#upload', :as => 'upload_locations'
	
	root :to => 'accounts#index', :as => :index

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :account_type
	belongs_to :user
  attr_protected :name
  has_one :default_account
end

app/models/account_type.rb
class AccountType < ActiveRecord::Base
  attr_protected :name, :show_negated, :reimb_cat_name, :reimb_cat_code
	has_many :accounts
end

app/models/default_account.rb
class DefaultAccount < ActiveRecord::Base
  belongs_to :account
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
	
	has_many :accounts, :autosave => true
	has_many :locations, :autosave => true
	
	before_save :add_default_accounts
	
	def add_default_accounts
		default_accounts = Account.joins(:default_account)
				
    default_accounts.each do |default_account|    
      account = Account.create
      account.name = default_account.name
      default_account.attributes.each do |name, value|
        account[name] = value
      end      
           
      account.user = self
      self.accounts << account
    end
    
    return self.ensure_authentication_token	
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_filter :authenticate_user!

  # GET /accounts
  # GET /accounts.json
  def index
		#Account.all
    @accounts = current_user.accounts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])
		@account.user = current_user

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/controllers/token_sessions_controller.rb
class TokenSessionsController < Devise::SessionsController
	skip_before_filter :verify_authenticity_token

	def create
		email = params[:email]
		password = params[:password]
		if not email.nil? and not password.nil?
			@user=User.find_by_email(email.downcase)
			@user.ensure_authentication_token!
      if @user.valid_password?(password)
      	 render :status=>200, :json=>{:auth_token=>@user.authentication_token}
      	 return
      end
		end
		render :status=>401, :json=>{:message=>"Invalid login."}
   end
 
  def destroy
    @user=User.find_by_authentication_token(params[:auth_token])
    if @user.nil?
      render :status=>404, :json=>{:message=>"Invalid token."}
    else
      @user.reset_authentication_token!
      render :status=>200, :json=>{:auth_token=>params[:auth_token]}
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<%= link_to 'New Account', new_account_path %>

<br />

<table>
  <tr>
    <th>Name</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
  	<td><%= account.name %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/home/index.html.erb
You successfully logged in!
You are logged in as <%= @user.email %>
<br>
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finance Tool Prototype</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">

<div id="header">
	<h1>Finance Tool</h1>
	<h2>Enter your reimbursements faster.</h2>
</div>

<div id="content">
<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
<br/>
<%= yield %>
</div>

<div id="footer">
&copy 2012 David Raffensperger
</div>

</div>

</body>
</html>